# Generated by Django 4.0.6 on 2022-08-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Investidor',
                'verbose_name_plural': 'Investidores',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Valor Investido')),
                ('created', models.DateField(verbose_name='Data do Investimento')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.owner', verbose_name='Nome Investidor')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
    ]
