# Generated by Django 4.0.6 on 2022-08-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='withdraw',
            field=models.DateField(null=True, verbose_name='Data do Resgate'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='created',
            field=models.DateField(verbose_name='Data da Aplicação'),
        ),
    ]
