# Generated by Django 4.0.6 on 2022-08-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0003_remove_investment_withdraw_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawinvestment',
            options={'verbose_name': 'Resgate Investimento', 'verbose_name_plural': 'Resgate Investimentos'},
        ),
        migrations.AddField(
            model_name='withdrawinvestment',
            name='amount_withdraw',
            field=models.PositiveIntegerField(default=1, verbose_name='Valor Investido'),
            preserve_default=False,
        ),
    ]
