# Generated by Django 4.0.1 on 2022-08-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0004_alter_withdrawinvestment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='withdrawal',
            field=models.DateField(null=True, verbose_name='Saque da Aplicação'),
        ),
        migrations.DeleteModel(
            name='WithdrawInvestment',
        ),
    ]
