# Generated by Django 4.0.6 on 2022-08-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0005_investment_withdrawal_delete_withdrawinvestment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='bank',
            field=models.CharField(choices=[('1', 'Banco do Brasil'), ('2', 'Caixa Econômica Federal'), ('3', 'Banco Itau'), ('4', 'Banco Bradesco'), ('5', 'Banco Santander'), ('6', 'Banco BTG'), ('7', 'Banco Inter'), ('8', 'XP Investimentos')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
